spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${JWT_ISSUER_URI}"
          jwk-set-uri: "${JWT_JWK_SET_URI}"
  datasource:
    driver-class-name: "org.postgresql.Driver"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    hikari:
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:9}
      connection-timeout: 60000
      initialization-fail-timeout: 60000
      minimum-idle: 3
      connection-test-query: "SELECT 1"
  jpa:
    hibernate:
      ddl-auto: "${JPA_HIBERNATE_DDL_AUTO:validate}"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  liquibase:
    change-log: "classpath:db/changelog/master.xml"
    clear-check-sums: true
    enabled: true

# Common Eureka config
eureka:
  client:
    service-url:
      defaultZone: "${EUREKA_URL}"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Common security config
security:
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
    allowed-headers: "*"
    allow-credentials: false
    max-age: 3600

# Common logging/tracing
management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  tracing:
    sampling:
      probability: 1.0

keycloak:
  admin:
    api:
      base-url: "${KEYCLOAK_ADMIN_API_BASE_URL}"
  token:
    api:
      base-url: "${KEYCLOAK_TOKEN_API_BASE_URL}"
  client:
    id: "${KEYCLOAK_CLIENT_ID}"
    secret: "${KEYCLOAK_CLIENT_SECRET}"
  realm:
    name: "${KEYCLOAK_REALM_NAME}"

logging:
  level:
    root: INFO
    cm.fastrelay.usermanager: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.http.client: DEBUG
    org.springframework.security: DEBUG
