spring:
  application:
    name: "${SPRING_APPLICATION_NAME:gateway}"

  cloud:
    gateway:
      mvc:
        routes:
          - id: usermanager
            uri: lb://usermanager
            predicates:
              - Path=/usermanager/**
          - id: image
            uri: lb://image
            predicates:
              - Path=/image/**
          - id: business
            uri: lb://business
            predicates:
              - Path=/business/**
          - id: product
            uri: lb://product
            predicates:
              - Path=/product/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: "${SERVER_PORT:8060}"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
