spring:
  application:
    name: "${SPRING_APPLICATION_NAME:order}"
  datasource:
    url: "${DB_URL}"
  kafka:
    bootstrap-servers: "kafka:29092"
    consumer:
      group-id: "order-service"
      auto-offset-reset: "earliest"
      enable-auto-commit: false
      isolation-level: "read_committed"
    topic:
      user-created: "user-created"
