spring:
  application:
    name: "${SPRING_APPLICATION_NAME:product}"
  datasource:
    url: "${DB_URL}"
  kafka:
    bootstrap-servers: "kafka:29092"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      properties:
        # for production
        acks: "all"
        retries: "3"
        batch.size: "16384"
        linger.ms: "1"
        buffer.memory: "33554432"
    topic:
      product-created: "product-created"
      promotion-created: "promotion-created"

application:
  promotion:
    batch:
      cron: "0 */5 * * * *"